# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleJsonParse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'FirebaseAnalytics'
pod 'FirebaseFirestore'
pod 'FirebaseCore'
pod 'Firebase' 
pod 'SDWebImageSwiftUI'
pod "Flags"


  # Pods for SimpleJsonParse
  pod 'Alamofire', '~> 4.9.1'
  pod 'SwiftyJSON'

end
